Feautre: Multiple spelling issues fix
plone/training pull request #594
Opened 2022-03-13 10:15 UTC by avimishra18

# Features
This Pull Request solves the following issues relating to the `make spellcheck` command. 

1. Reduced ~25% of *misspelled words* from 1296 to 956 by:
   1. Adding words to `spelling_wordlist.txt`
   1. Corrected spellings in some file
1. Possibly Fixed All: `WARNING: image file not readable: <filename.ext>`. Including but not limited to these files: 
   1. [Customize CSS/Less Variables](https://training.plone.org/5/theming_plone_5/basic.html#customize-css-less-variables)
   1. [Exercise 3 - The <drop> Directive](https://training.plone.org/5/theming_plone_5/ttw-advanced-2.html#exercise-3-the-drop-directive)
   1. [Exercise 1 - Create A New Theme That Inherits From Barceloneta](https://training.plone.org/5/ttw/ttw-advanced-2.html#exercise-1-create-a-new-theme-that-inherits-from-barceloneta)
1. Removed all *misspelled words* from the following training: 
   1. React
   1. Volto

[Community Post Link](https://community.plone.org/t/information-for-interested-gsoc-students-2022/14893/31?u=avimishra18)

2022-03-13 19:56 UTC, stevepiercy requested changes
First I want to acknowledge that this is a huge effort on your part. I greatly appreciate the time you put into this.

After incorporating suggestions in this file, we should determine whether instances in the documentation should be changed. It depends on the usage.

Acronyms should be ignored by spellcheck and not be in `spelling_wordlist.txt`. Also:

- If the acronym is in narrative text, it should be uppercased. For example "cli" -> "CLI".
- If the acronym is an inline literal or part of a command, then it should be surrounded by backticks or part of a code-block.
- If the acronym is a GUI or navigation element, then it should become a `{guilabel}` or `{menuselection}` MyST directive.

Thank you so much!

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +repo
Remove. This should be spelled out as "repository".

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +restapi
This should be an inline literal or part of `plone.restapi` as an inline literal.

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +styleguide
Two words. Should be fixed in the docs.

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +stylesheets
The above two entries should be two words and fixed in the docs.

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +stylesheet
```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
>  toLocalizedTime
Convert to inline literal.

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +ttf
Acronym.

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
>  ttw
Acronym.
```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +txt
This is likely part of a filename that should become an inline literal.

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +underlaying
The correct word in the documentation should be "underlying".

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +useEffect
Convert to an inline literal.

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +volto
Possibly convert to inline literal or make it a proper noun as "Volto".

```suggestion
```

2022-03-13 19:56 UTC, stevepiercy commented on docs/wsgi/uwsgi.md
> +POSIX capabilities are enabled in Ubuntu's uwsgi by default, so we only need to add two lines to `/etc/uwsgi-emperor/emperor.ini` to enable tyrannt mode:
```suggestion
POSIX capabilities are enabled in Ubuntu's uWSGI by default, so we only need to add two lines to `/etc/uwsgi-emperor/emperor.ini` to enable tyrant mode:
```

2022-03-14 00:36 UTC, avimishra18 commented
First of all, thank you @stevepiercy for such a fast and detailed review. I have incorporated the changes as you suggested. Please, review again.

2022-03-14 09:13 UTC, stevepiercy requested changes
Just one change in this file, but I do not see changes in the docs that might still need to be addressed, such as converting them to inline literals.

2022-03-14 16:37 UTC, avimishra18 commented on docs/spelling_wordlist.txt
> +mscorefonts
This already in triple backticks. Do I need to surround ttf-mscorefonts-installer with backticks too?
```
```{warning}
Make sure you have the 'Comic Sans MS' font installed. This is the `ttf-mscorefonts-installer` package for the Debian linux distribution.
```
```

2022-03-14 17:29 UTC, avimishra18 commented on docs/spelling_wordlist.txt
> +config
`config` might mean something different as it may be an identifier. So, I think respective authors should update it.

2022-03-14 17:47 UTC, merged

2022-03-14 22:07 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +config
Agreed. Resolving.

2022-03-14 22:12 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +controlpanels
Actually I just realized that these words should exist in the spellcheck dictionary. As such, if we remove these entries, I think spellcheck will not flag them as misspellings. Would you please try that experiment and let me know?

2022-03-14 22:13 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +controlpanels
I will also unresolve similar items. If an entry is a common US English word that exists in the spellcheck, then it should not be flagged as a misspelling.

2022-03-14 22:13 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +developement
Possibly remove as a correct spellcheck dictionary spelling?

2022-03-14 22:14 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +editbar
Possibly remove as a correct spellcheck dictionary spelling?

2022-03-14 22:20 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +mscorefonts
Yes. Three (and more when nested) backticks are a MyST directive block delimiter. Inline literals within the block need to be surrounded by single backticks.

2022-03-14 22:21 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +nodejs
Yes, use proper casing in a narrative context, but not when in a command or inline literal.

2022-03-14 22:22 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +overriden
Possibly remove as a correct spellcheck dictionary spelling?

2022-03-14 22:25 UTC, stevepiercy commented on docs/spelling_wordlist.txt
> +volto
Agreed. Not my idea of fun. :wink:

2022-03-14 22:26 UTC, stevepiercy commented
@avimishra18 I just enabled branch protection on `plone/training@main` that requires a member of the `plone/documentation-team` to merge open PRs and push to `main`. Previously it allowed any person who signed the Plone CA to push to `main`. This will prevent future "oopsies" from new contributors.

Meanwhile, please create a new PR that updates the Training docs content according to my review in this PR including items that I just now unresolved and made comments on, and link to this PR as a reference. Thank you!