Initial commit, add Architecture and Backend
plone/training pull request #630
Opened 2022-08-21 16:23 UTC by sneridagh

2022-10-02 17:57 UTC, tiberiuichim commented on docs/effective-volto/deployment/simple.md
> +For SSL support is recommended to use a reverse proxy of your choice that points to Volto port and an API rewrite eg. `/api` in your server. This is the nginx configuration:
Is this still true?

2022-10-10 12:41 UTC, stevepiercy requested changes
Thank you for doing this! I hope more trainers give their topmatter some search engine love.

I made some nitpicky details suggestions regarding proper names.

Also there is an extra space everywhere that is easier to do a global find and replace than to create lots of demoralizing review comments.

```diff
- "property=og:title":  "
+ "property=og:title": "
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/how-an-add-on-works.md
> +    "description": "How does a Volto add-on works?"
Remove the extra "s" from all the topmatter entries and first heading.

```suggestion
    "description": "How does a Volto add-on work?"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/theme.md
> +    "keywords": "Volto, Plone, Semantic-UI, CSS, Volto theme"
```suggestion
    "keywords": "Volto, Plone, Semantic UI, CSS, Volto theme"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/dependencies.md
> +    "keywords": "Volto, Plone, Volto add-ons, Javascript, Javascript dependencies"
```suggestion
    "keywords": "Volto, Plone, Volto add-ons, JavaScript, JavaScript dependencies"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/semanticui.md
> +    "keywords": "Volto, Plone, Semantic-UI, CSS, Volto theme"
```suggestion
    "keywords": "Volto, Plone, Semantic UI, CSS, Volto theme"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/semanticui.md
> +    "description": "Extending SemanticUI"
```suggestion
    "description": "Extending Semantic UI"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/semanticui.md
>  # Extending SemanticUI
```suggestion
# Extending Semantic UI
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/semanticui.md
> +    "property=og:description": "Extending SemanticUI"
```suggestion
    "property=og:description": "Extending Semantic UI"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/semanticui.md
> +    "property=og:title":  "Extending SemanticUI"
```suggestion
    "property=og:title":  "Extending Semantic UI"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/use-repo-addon.md
> +    "description": "Configure a non-released add-on from an existing repository"
```suggestion
    "description": "Configure an unreleased add-on from an existing repository"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/use-repo-addon.md
> +    "property=og:description": "Configure a non-released add-on from an existing repository"
```suggestion
    "property=og:description": "Configure an unreleased add-on from an existing repository"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/use-repo-addon.md
> +    "property=og:title":  "Configure a non-released add-on from an existing repository"
```suggestion
    "property=og:title":  "Configure an unreleased add-on from an existing repository"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/use-repo-addon.md
>  # Configure a non-released add-on from an existing repository
```suggestion
# Configure an unreleased add-on from an existing repository
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/what-is-an-addon.md
> +    "description": "What is a Volto addon"
```suggestion
    "description": "What is a Volto add-on"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/what-is-an-addon.md
> +    "property=og:description": "What is a Volto addon"
```suggestion
    "property=og:description": "What is a Volto add-on"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/what-is-an-addon.md
> +    "property=og:title":  "What is a Volto addon"
```suggestion
    "property=og:title":  "What is a Volto add-on"
```

2022-10-10 12:41 UTC, stevepiercy commented on docs/effective-volto/addons/what-is-an-addon.md
>  # What is a Volto addon
```suggestion
# What is a Volto add-on
```

2022-10-10 12:44 UTC, tiberiuichim commented
@stevepiercy Many thanks for the review! I'll apply your suggestions

2022-10-10 12:52 UTC, stevepiercy requested changes
A few more nitpicky details that are easier to fix with a global find and replace than a bunch of suggestions.

```diff
- "property=og:title":  "
+ "property=og:title": "
```

2022-10-10 13:18 UTC, stevepiercy approved these changes
I won't have time to review this entire epic training before tomorrow, and I trust you did your best, so I approve. Let's make sure that no new warnings or errors are introduced—specifically in MyST topmatter—then clean it up during the training. Please encourage participants to submit pull requests. Thank you!

2022-10-10 13:18 UTC, stevepiercy commented on docs/effective-volto/about_effective_volto.md
> +  "keywords": ""
Please add MyST topmatter. Also make sure that `myst` is the root key wherever you create a new page and the remaining keys are indented appropriately.

```
myst:
  html_meta:
    "description": "About Effective Volto"
    "property=og:description": "About Effective Volto"
    "property=og:title": "About Effective Volto"
    "keywords": "Volto, Tiberiu Ichim, Víctor Fernández de Alba"
```

2022-10-10 14:06 UTC, merged