Update setup.md
plone/training pull request #650
Opened 2022-10-10 08:32 UTC by loechel

Update on Node Setup and Vagrant

2022-10-10 09:29 UTC, stevepiercy requested changes

2022-10-10 09:29 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +- [Vagrant](https://www.vagrantup.com/downloads) and VirtualBox or libvirt (Linux / macOS) (caution VirtualBox does not work on Apple Silicion)
```suggestion
- [Vagrant](https://www.vagrantup.com/downloads) and VirtualBox or libvirt (Linux / macOS).
```

2022-10-10 09:29 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +Use it to install latest version of Node LTS (currently v16.17.1) and NPM (hint: check if a newer minor or bugfix release is available).
```suggestion
Use it to install the latest version of Node LTS (currently v16.17.1) and NPM (hint: check if a newer minor or bugfix release is available).
```

2022-10-10 13:05 UTC, stevepiercy approved these changes

2022-10-11 06:48 UTC, ericof approved these changes

2022-10-11 06:49 UTC, merged