using npx for run critical-css script
plone/training pull request #693
Opened 2022-11-14 09:21 UTC by mamico

2022-11-14 09:47 UTC, stevepiercy requested changes

2022-11-14 09:47 UTC, stevepiercy commented on docs/effective-volto/development/criticalCSS.md
> +```
Always add a lexer to code blocks

```suggestion
```shell
```

2022-11-14 10:18 UTC, tiberiuichim approved these changes

2022-11-16 23:10 UTC, stevepiercy approved these changes

2022-11-16 23:10 UTC, merged