Fixed the relative path
plone/training pull request #722
Opened 2023-03-04 19:51 UTC by SaiRev0

Fixed the relative path as it was not correct

2023-03-04 20:56 UTC, stevepiercy requested changes
Restore deleted comma.

2023-03-04 20:56 UTC, stevepiercy commented on docs/volto/override-components.md
> +So for example if we want to replace the logo, which is located in Volto at `omelette/src/components/theme/Logo/Logo.svg`
```suggestion
So for example if we want to replace the logo, which is located in Volto at `omelette/src/components/theme/Logo/Logo.svg`,
```

2023-03-05 09:40 UTC, stevepiercy approved these changes
Thank you! If no one from the Volto team on Discord answers my call to review this PR within a few days, then ping me to just merge it.

2023-03-05 09:43 UTC, merged

2023-03-05 09:44 UTC, ksuess commented
Thank you @SaiRev0 for reporting and even fixing!

2023-03-05 10:00 UTC, SaiRev0 commented
@ksuess No Worrie always ready to help and to give back to the community that has helped me a lot.