Fixed some typos in Mastering Plone 6 > 4, 11, 12
plone/training pull request #733
Opened 2023-03-08 15:27 UTC by curiousyuvi

2023-03-08 22:55 UTC, stevepiercy requested changes
English grammar fixes.

2023-03-08 22:55 UTC, stevepiercy commented on docs/mastering-plone/case.md
> +The conference-website we want to create should be reusable in the following years so some things should be configurable.
You might see an overabundance of hyphenated words, such as this. Germanic languages do this a lot, but in English it is less common.

```suggestion
The conference website we want to create should be reusable in the following years, so some things should be configurable.
```

2023-03-08 22:55 UTC, stevepiercy commented on docs/mastering-plone/case.md
> +- Allow some available to be configurable by a admin in a controlpanel
This sentence does not make sense. It is missing a word after "available", or perhaps the intent is "availability"? I am not sure. Would you please look elsewhere in this Training to infer what it should be?

```suggestion
- Allow some available to be configurable by an admin in a control panel
```

2023-03-08 22:55 UTC, stevepiercy commented on docs/mastering-plone/volto_overrides.md
> +As we are in the html part of our React component, we embrace the Javascript code in curly braces.
```suggestion
As we are in the HTML part of our React component, we surround the JavaScript code with curly braces.
```

2023-03-09 04:12 UTC, stevepiercy commented
@ksuess @pbauer do either of you know what is the intent of this sentence? It's missing a word.

https://github.com/plone/training/pull/733/files#diff-dd0fff211cdaf08da26e0acdce999187e533ccf36f118d9605d825471169fdabR81

2023-03-09 06:53 UTC, ksuess requested changes

2023-03-09 06:53 UTC, ksuess commented on docs/mastering-plone/case.md
> +- Allow some available to be configurable by an admin in a control panel
```suggestion
- Allow some settings to be configurable by an admin in a control panel
```

2023-03-09 07:21 UTC, stevepiercy approved these changes
Thank you!

2023-03-09 07:21 UTC, merged