Update footer.md
plone/training pull request #775
Opened 2023-07-21 12:51 UTC by claudiaifrim

Fix import error for Grid.

2023-07-21 14:05 UTC, ksuess requested changes
Good catch!

2023-07-21 14:05 UTC, ksuess commented on docs/voltohandson/footer.md
> +We will also need the Grid component from semantic ui:
```suggestion
We also need the `Grid` component from Semantic UI
```
For consistency: presence

2023-07-21 19:24 UTC, stevepiercy approved these changes
Thank you!

2023-07-21 19:26 UTC, stevepiercy commented
Oops I meant to provide the same suggestions as @ksuess. With those changes I approve.

2023-08-16 09:47 UTC, stevepiercy approved these changes
I made the correction, and approve. Ready to merge.

2023-08-16 10:02 UTC, merged