Plone deployment training minor fix proposal
plone/training pull request #809
Opened 2023-10-07 15:47 UTC by deruosi

- some minor fix to ease following the training istructions (IMHO)
- added a troubleshooting paragraph with sone other reported issues

2023-10-07 18:03 UTC, stevepiercy requested changes
Mostly some MyST syntax fixes and style guide things. Otherwise this is good.

2023-10-07 18:03 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +```
````suggestion
```shell
````

2023-10-07 18:03 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +See also [https://docs.docker.com/engine/reference/commandline/system_prune/](https://docs.docker.com/engine/reference/commandline/system_prune/)
MyST syntax.

````suggestion
```{seealso}
See also https://docs.docker.com/engine/reference/commandline/system_prune/.
```
````

2023-10-07 18:03 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +You can also configure settings for Docker Desktop. Under `Prefences > Resources > Advanced`, you can configure appropriate settings for virtual disk limit and memory.
```suggestion
You can also configure settings for Docker Desktop.
Under {guilabel}`Prefences > Resources > Advanced`, you can configure appropriate settings for virtual disk limit and memory.
```

2023-10-07 18:03 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +See also:
````suggestion
```{seealso}
See also
- [Change Docker Desktop settings on Mac](https://docs.docker.com/desktop/settings/mac/#advanced)
- [Change Docker Desktop settings on Windows](https://docs.docker.com/desktop/settings/windows/#advanced)
- [Change Docker Desktop settings on Linux](https://docs.docker.com/desktop/settings/linux/#advanced)
```
````

2023-10-09 14:57 UTC, deruosi commented
thanks @stevepiercy , I've committed your changes. Have I to *Close with comment* (which seems the only option I have from github) and make a new pull request?

2023-10-10 08:23 UTC, stevepiercy commented
Would you please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html)? I assumed you had already signed the agreement.

2023-10-10 08:29 UTC, stevepiercy requested changes
There were some duplicated lines that need to be removed.

2023-10-10 08:29 UTC, stevepiercy commented on docs/plone-deployment/project-edit.md
> +If the project was running, halt the Frontend with {kbd}`Ctrl-C`. Restart it with `make start-frontend`
The project was stopped in the previous step.

```suggestion
```

2023-10-10 08:29 UTC, stevepiercy commented on docs/plone-deployment/project-edit.md
> +Start your project with: `make start-backend` and `make start-frontend` on different shells.
Duplicated by below line.

```suggestion
```

2023-10-10 08:29 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +- [Change Docker Desktop settings on Mac](https://docs.docker.com/desktop/settings/mac/#advanced)
Duplicated above.

```suggestion
```

2023-10-10 08:29 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +- [Change Docker Desktop settings on Windows](https://docs.docker.com/desktop/settings/windows/)
Duplicated above.

```suggestion
```

2023-10-10 08:29 UTC, stevepiercy commented on docs/plone-deployment/setup.md
> +- [Change Docker Desktop settings on Linux](https://docs.docker.com/desktop/settings/linux/)
Duplicated above.

```suggestion
```

2023-10-10 11:01 UTC, deruosi commented
I signed the agreement yesterday, just before accepting and committing the changes

I realize the process is more complex than I thought: sorry for the inconvenience. By the way: next time I will create a new branch even for the (supposed) minor fix, I promise!

2023-10-10 15:51 UTC, stevepiercy requested changes
One more minor change, and I approve, pending review and acceptance of your Plone Contributor Agreement. Thank you for your patience!

2023-10-11 07:45 UTC, stevepiercy approved these changes

2023-10-11 07:47 UTC, stevepiercy commented
@deruosi this looks good. Please let me know when your Plone Contributor Agreement is approved, then I can merge this PR. Thank you!

2023-10-11 10:31 UTC, deruosi commented
@stevepiercy my Plone developer agreement was processed a few hours ago: I just joined the Plone Contributors team. Thanks!

2023-10-12 09:05 UTC, merged

2023-10-12 09:05 UTC, stevepiercy commented
@deruosi thank you!