Update project.md
plone/training pull request #840
Opened 2024-03-13 15:26 UTC by agan-k

Dead links for Plone Documentation. Updated with the ones from the [cookie-cutter-plone-starter](https://github.com/collective/cookiecutter-plone-starter?tab=readme-ov-file).

<img width="400" alt="Screenshot 2024-03-13 at 11 22 40 AM" src="https://github.com/plone/training/assets/25995514/61ba8192-14dd-4f3d-b27c-a6c01024123f">

2024-03-13 18:46 UTC, stevepiercy requested changes
Use correct anchors.

2024-03-13 18:46 UTC, stevepiercy commented on docs/effective-volto/getting-started/project.md
> +First install `nvm` and latest Node.JS according to the [Plone documentation](https://6.docs.plone.org/install/create-project.html#pre-requisites-for-installation).
```suggestion
First install `nvm` and latest Node.JS according to the [Plone documentation](https://6.docs.plone.org/install/create-project.html#nvm).
```

2024-03-13 18:46 UTC, stevepiercy commented on docs/effective-volto/getting-started/project.md
> +After that, install Yeoman according to the [Plone documentation](https://6.docs.plone.org/install/create-project.html#pre-requisites-for-installation).
```suggestion
After that, install Yeoman according to the [Plone documentation](https://6.docs.plone.org/install/create-project.html#yeoman-and-the-volto-boilerplate-generator).
```

2024-03-13 18:46 UTC, stevepiercy commented on docs/effective-volto/getting-started/project.md
> +Finally, install `yarn` according to the [Plone documentation](https://6.docs.plone.org/install/create-project.html#pre-requisites-for-installation).
```suggestion
Finally, install `yarn` according to the [Plone documentation](https://6.docs.plone.org/install/create-project.html#yarn).
```

2024-03-13 18:47 UTC, stevepiercy commented
@agan-k please read and follow https://training.plone.org/contributing/index.html.

2024-03-13 19:28 UTC, stevepiercy approved these changes
LGTM, but we need to wait for your permission to publish before we can merge. Please post a comment when you have been approved. Thank you!

2024-03-16 07:34 UTC, stevepiercy commented
@agan-k did you submit a Plone Contributor Agreement?

2024-03-16 13:24 UTC, agan-k commented
> @agan-k did you submit a Plone Contributor Agreement?

@stevepiercy I did about 3 days ago.

2024-03-18 14:51 UTC, agan-k commented
@stevepiercy the permission just came in.

2024-03-18 22:10 UTC, stevepiercy approved these changes

2024-03-18 22:13 UTC, merged

2024-03-18 22:13 UTC, stevepiercy commented
Thank you!